apiVersion: v1
kind: Service
metadata:
  name: backend-lab04
  labels:
    name: backend-lab04
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: backend-lab04
  type: NodePort
